[package]
name = "balso-cli"
version.workspace = true
edition.workspace = true
description = "CLI for Balsa molecular line notation."
homepage.workspace = true
license.workspace = true

[dependencies]
balso-graph.workspace = true
balso-parser.workspace = true

facet.workspace = true
facet-args.workspace = true
