[package]
name = "balso-wasm"
version.workspace = true
edition.workspace = true
description = "WebAssembly bindings for the Balsa molecular line notation."
homepage.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
balso-core.workspace = true
balso-parser.workspace = true

pretty_assertions.workspace = true
