[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2021"
description = "Reference implementation for the Balsa molecular line notation."
readme = "README.md"
homepage = "https://github.com/chillcicada/balso/"
license = "MIT"

[workspace.dependencies]
balso-core = { path = "crates/balso-core" }
balso-graph = { path = "crates/balso-graph" }
balso-parser = { path = "crates/balso-parser" }
balso-tree = { path = "crates/balso-tree" }

facet = "0.46.5"
facet-args = "0.43.2"

pretty_assertions = "1.4.1"

[profile.release]
opt-level = 3
strip = true
lto = true
panic = "abort"
codegen-units = 1
