[package]
name = "balso"
version.workspace = true
edition.workspace = true
description = "Plotting and visualization utilities for Balsa molecular line notation."
homepage.workspace = true
license.workspace = true

[dependencies]
balso-core.workspace = true
balso-graph.workspace = true
balso-layout.workspace = true
balso-parser.workspace = true
nalgebra = "0.33"
pretty_assertions.workspace = true
